# Generated by Django 5.2.7 on 2025-10-15 15:17

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='uploads/default.png', null=True, upload_to=shop.models.getFileName),
        ),
    ]
